Repository Turfjs/turf, pull requests merged in 2018-03, with the labels that each got.

#1278 Add test case for segmentEach Polygon bug
  packages/turf-meta/index.mjs
  packages/turf-meta/test.js
Labels: bug-fix, testing

#1293 Use turf/boolean-intersects in square-grid. Resolves #1215
  packages/turf-square-grid/bench.js
  packages/turf-square-grid/index.js
  packages/turf-square-grid/package.json
  packages/turf-square-grid/test.js
  packages/turf-square-grid/test/in/issue-1215.geojson
  packages/turf-square-grid/test/out/big-bbox.geojson
  packages/turf-square-grid/test/out/fiji-10-miles.geojson
  packages/turf-square-grid/test/out/issue-1215.geojson
  packages/turf-square-grid/test/out/london-20-miles.geojson
  packages/turf-square-grid/test/out/piedemont-mask.geojson
  packages/turf-square-grid/test/out/properties.geojson
  packages/turf-square-grid/test/out/resolute.geojson
Labels: bug-fix

#1327 Convert Quadrat to Typescript
  packages/turf-boolean-disjoint/index.d.ts
  packages/turf-boolean-disjoint/index.ts
  packages/turf-boolean-disjoint/package.json
  packages/turf-boolean-disjoint/tsconfig.json
  packages/turf-boolean-disjoint/tslint.json
  packages/turf-boolean-intersects/index.d.ts
  packages/turf-boolean-intersects/package.json
  packages/turf-boolean-intersects/tsconfig.json
  packages/turf-boolean-intersects/tslint.json
  packages/turf-line-intersect/index.d.ts
  packages/turf-line-intersect/index.ts
  packages/turf-line-intersect/package.json
  packages/turf-line-intersect/tsconfig.json
  packages/turf-line-intersect/tslint.json
  packages/turf-line-segment/index.d.ts
  packages/turf-line-segment/index.ts
  packages/turf-line-segment/package.json
  packages/turf-line-segment/tsconfig.json
  packages/turf-line-segment/tslint.json
  packages/turf-polygon-to-line/index.d.ts
  packages/turf-polygon-to-line/index.ts
  packages/turf-polygon-to-line/package.json
  packages/turf-polygon-to-line/tsconfig.json
  packages/turf-polygon-to-line/tslint.json
  packages/turf-polygon-to-line/types.ts
  packages/turf-quadrat-analysis/.gitignore
  packages/turf-quadrat-analysis/bench.js
  packages/turf-quadrat-analysis/index.d.ts
  packages/turf-quadrat-analysis/index.js
  packages/turf-quadrat-analysis/index.ts
  packages/turf-quadrat-analysis/package.json
  packages/turf-quadrat-analysis/test.js
  packages/turf-quadrat-analysis/tsconfig.json
  packages/turf-quadrat-analysis/tslint.json
  packages/turf-random/index.d.ts
  packages/turf-random/index.ts
  packages/turf-random/package.json
  packages/turf-random/tsconfig.json
  packages/turf-random/tslint.json
  packages/turf-random/types.ts
  packages/turf-square-grid/index.d.ts
  packages/turf-square-grid/index.ts
  packages/turf-square-grid/package.json
  packages/turf-square-grid/tsconfig.json
  packages/turf-square-grid/tslint.json
  packages/turf-square-grid/types.ts
  yarn.lock
Labels: typescript

#1328 Convert @turf/helpers to Typescript
  packages/turf-clone/index.d.ts
  packages/turf-clone/index.ts
  packages/turf-clone/package.json
  packages/turf-clone/tsconfig.json
  packages/turf-clone/tslint.json
  packages/turf-clone/types.ts
  packages/turf-concave/index.d.ts
  packages/turf-concave/index.ts
  packages/turf-concave/lib/turf-dissolve.d.ts
  packages/turf-concave/lib/turf-dissolve.ts
  packages/turf-concave/lib/turf-line-dissolve.d.ts
  packages/turf-concave/lib/turf-line-dissolve.ts
  packages/turf-concave/lib/turf-polygon-dissolve.d.ts
  packages/turf-concave/lib/turf-polygon-dissolve.ts
  packages/turf-concave/package.json
  packages/turf-concave/test.js
  packages/turf-concave/tsconfig.json
  packages/turf-concave/tslint.json
  packages/turf-convex/index.d.ts
  packages/turf-convex/index.ts
  packages/turf-convex/package.json
  packages/turf-helpers/index.d.ts
  packages/turf-helpers/index.ts
  packages/turf-helpers/lib/geojson.d.ts
  packages/turf-helpers/package.json
  packages/turf-helpers/test.js
  packages/turf-helpers/tsconfig.json
  packages/turf-helpers/tslint.json
  packages/turf-helpers/types.ts
  packages/turf-rhumb-destination/index.d.ts
  packages/turf-rhumb-destination/package.json
  packages/turf-rhumb-destination/test.js
  packages/turf-tin/index.d.ts
  packages/turf-tin/index.ts
  packages/turf-tin/package.json
  packages/turf-tin/tsconfig.json
  packages/turf-tin/tslint.json
  packages/turf-tin/types.ts
  tsconfig.json
  yarn.lock
Labels: typescript

#1336 New module: moran-index.
  packages/turf-distance-weight/.gitignore
  packages/turf-distance-weight/LICENSE
  packages/turf-distance-weight/README.md
  packages/turf-distance-weight/bench.js
  packages/turf-distance-weight/index.d.ts
  packages/turf-distance-weight/index.ts
  packages/turf-distance-weight/package.json
  packages/turf-distance-weight/test.js
  packages/turf-distance-weight/test/in/columbus.json
  packages/turf-distance-weight/test/in/point.json
  packages/turf-distance-weight/tsconfig.json
  packages/turf-distance-weight/tslint.json
  packages/turf-moran-index/.gitignore
  packages/turf-moran-index/LICENSE
  packages/turf-moran-index/README.md
  packages/turf-moran-index/bench.js
  packages/turf-moran-index/index.d.ts
  packages/turf-moran-index/index.ts
  packages/turf-moran-index/package.json
  packages/turf-moran-index/test.js
  packages/turf-moran-index/test/in/columbus.json
  packages/turf-moran-index/test/in/point.json
  packages/turf-moran-index/tsconfig.json
  packages/turf-moran-index/tslint.json
  packages/turf-nearest-neighbor-analysis/index.d.ts
Labels: new-module
